### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sahara101** [c99koder/personal-influxdb#26]
Hello, upon running the pip command I am getting this error:

python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
          __import__('pkg_resources.extern.packaging.specifiers')
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 24, in <module>
          from .utils import canonicalize_version
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/tags.py", line 5, in <module>
          import logging
        File "/tmp/pip-install-nmi5pbb_/logging_593e45d1e049402eafcf6c9c41b75056/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

Thanks!

**Comment by c99koder** [comment]
Remove `logging` from the list of packages, as it's not compatible with the version of Python you have installed.
